name: Update Market Data

on:
  schedule:
    - cron: '*/1 * * * *'  # 매 1분마다 실행 (UTC 기준)

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pymssql

    - name: Run data update script
      run: python fetch_market_data.py